### PR TITLE
fix: remove pkgInfo dependency to allow webpack bundling

### PR DESCRIPTION
**Pull request by emyann**
`pkgInfo` fails when trying to bundle this package using Webpack. This pull request removes that dependency.

### CODE REVIEW

**Comment by eyaleizenberg** [comment]
@emyann Thank you for this! I went through 2 days of trial & errors until this finally worked for me! I would keep the export the same as it was before because:
1. It breaks backward compatibility.
2. It breaks the tests (for the same reason as #1).

@JMPerez can we get this merged and published afterwards please?

**Comment by JMPerez** [comment]
@eyaleizenberg I haven't had much time to look into this. At first sight, I would like to make sure this change doesn't break anything, and it passes whatever tests are run to check the build is correct. Can you guys fix the tests?

**Comment by eyaleizenberg** [comment]
Thanks for answering @JMPerez 
@emyann Can you please revert your change from this:
```
export default Strategy;
```

back to this:
```
exports.Strategy = Strategy;
```

It should fix everything (hopefully).

Thanks!

**Comment by eyaleizenberg** [comment]
@JMPerez It looks like @emyann is away/not responding. I've created my own fork with the changes and removed the irrelevant test. Build is now green: https://github.com/JMPerez/passport-spotify/pull/86

**Comment by emyann** [comment]
@eyaleizenberg Sorry I didn't have too much time to work on this. Thank you for the fix! 

@JMPerez  Feel free to close this if https://github.com/JMPerez/passport-spotify/pull/86 looks good to you.

**Comment by JMPerez** [comment]
Closed in favor of https://github.com/JMPerez/passport-spotify/pull/86

**Pull request closed without merging**
